### ISSUE TITLE
The question about CUDA version

### ISSUE THREAD

**Issue by Wangzesonga** [R-I-S-Khan/SHADE#1]
Your work are amazing, but when I ran setup.py I met the following errors: 

`ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    build_deps()
  File "setup.py", line 308, in build_deps
    build_caffe2(version=version,
  File "/root/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/root/anaconda3/envs/shade_conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '104']' returned non-zero exit status 1.`

I think it's due to the CUDA version not matching with PyTorch 1.7.0 because when I upgraded PyTorch to the latest version, the errors disappeared.

Could you please share with me the CUDA version you used in this experiment? Thank you.

My build environment:
cpu_info: Intel(R) Xeon(R) Gold 5320 CPU @ 2.20GHz
gpu_info: NVIDIA Tesla V100 32GB PCIe
memory: Samsung DDR4 512G
swapfile:4g used
cuda: "11.6"
python:3.8.10
pytorch:1.7.0
nvidia-driver:510.108.03
Ubuntu:20.04

**Comment by rkhan055** [comment]
Hi Zesong, Thanks for your interest in SHADE. Version conflicts and errors can be very annoying. Could you try with CUDA 10.1?

**Comment by Wangzesonga** [comment]
> Hi Zesong, Thanks for your interest in SHADE. Version conflicts and errors can be very annoying. Could you try with CUDA 10.1?

Thank you for your reply! After several days of attempts, I finally managed to successfully run your code. Your code is well-organized and the workflow is clearly written. My final CUDA version is 11.0, it works too.
